# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idiomaddadd.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 262)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.answer = QtWidgets.QLineEdit(self.groupBox)
        self.answer.setMaxLength(18)
        self.answer.setObjectName("answer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.answer)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.options = QtWidgets.QLineEdit(self.groupBox)
        self.options.setMaxLength(18)
        self.options.setObjectName("options")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.options)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加/修改题目"))
        self.groupBox.setTitle(_translate("Form", "添加题目（填空题）："))
        self.label_5.setText(_translate("Form", "问题："))
        self.label_8.setText(_translate("Form", "答案："))
        self.label_9.setText(_translate("Form", "选项："))
        self.pushButton_3.setText(_translate("Form", "确定提交"))
