# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsadd.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 671)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pixlabel = QtWidgets.QLabel(self.groupBox)
        self.pixlabel.setMinimumSize(QtCore.QSize(200, 100))
        self.pixlabel.setMaximumSize(QtCore.QSize(200, 200))
        self.pixlabel.setObjectName("pixlabel")
        self.gridLayout.addWidget(self.pixlabel, 2, 2, 2, 1)
        self.author = QtWidgets.QLineEdit(self.groupBox)
        self.author.setMaximumSize(QtCore.QSize(100, 16777215))
        self.author.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.author.setMaxLength(200)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 2, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(self.groupBox)
        self.title.setMaximumSize(QtCore.QSize(280, 16777215))
        self.title.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.title.setMaxLength(200)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cl1 = QtWidgets.QLabel(self.groupBox)
        self.cl1.setObjectName("cl1")
        self.gridLayout_2.addWidget(self.cl1, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.cb1 = QtWidgets.QPushButton(self.groupBox)
        self.cb1.setObjectName("cb1")
        self.gridLayout_2.addWidget(self.cb1, 0, 1, 1, 1)
        self.ct1 = QtWidgets.QTextEdit(self.groupBox)
        self.ct1.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ct1.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.ct1.setObjectName("ct1")
        self.gridLayout_2.addWidget(self.ct1, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.ct2 = QtWidgets.QTextEdit(self.groupBox)
        self.ct2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ct2.setObjectName("ct2")
        self.gridLayout_3.addWidget(self.ct2, 1, 0, 3, 1)
        self.cb2 = QtWidgets.QPushButton(self.groupBox)
        self.cb2.setObjectName("cb2")
        self.gridLayout_3.addWidget(self.cb2, 0, 1, 1, 1)
        self.cl2 = QtWidgets.QLabel(self.groupBox)
        self.cl2.setObjectName("cl2")
        self.gridLayout_3.addWidget(self.cl2, 1, 1, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ct3 = QtWidgets.QTextEdit(self.groupBox)
        self.ct3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ct3.setObjectName("ct3")
        self.gridLayout_4.addWidget(self.ct3, 1, 0, 3, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.cb3 = QtWidgets.QPushButton(self.groupBox)
        self.cb3.setObjectName("cb3")
        self.gridLayout_4.addWidget(self.cb3, 0, 1, 1, 1)
        self.cl3 = QtWidgets.QLabel(self.groupBox)
        self.cl3.setObjectName("cl3")
        self.gridLayout_4.addWidget(self.cl3, 1, 1, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.subbt = QtWidgets.QPushButton(self.groupBox)
        self.subbt.setObjectName("subbt")
        self.verticalLayout_2.addWidget(self.subbt)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.title, self.author)
        Form.setTabOrder(self.author, self.dateEdit)
        Form.setTabOrder(self.dateEdit, self.pushButton)
        Form.setTabOrder(self.pushButton, self.ct1)
        Form.setTabOrder(self.ct1, self.cb1)
        Form.setTabOrder(self.cb1, self.ct2)
        Form.setTabOrder(self.ct2, self.cb2)
        Form.setTabOrder(self.cb2, self.ct3)
        Form.setTabOrder(self.ct3, self.cb3)
        Form.setTabOrder(self.cb3, self.subbt)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加/修改新闻"))
        self.groupBox.setTitle(_translate("Form", "添加/修改新闻："))
        self.pixlabel.setText(_translate("Form", "封面图片预览"))
        self.pushButton.setText(_translate("Form", "添加封面图片"))
        self.label_6.setText(_translate("Form", "作者："))
        self.label_8.setText(_translate("Form", "发布日期："))
        self.label_5.setText(_translate("Form", "标题："))
        self.cl1.setText(_translate("Form", "内容1图片预览："))
        self.label_9.setText(_translate("Form", "内容1："))
        self.cb1.setText(_translate("Form", "添加内容1图片"))
        self.label_11.setText(_translate("Form", "内容2："))
        self.cb2.setText(_translate("Form", "添加内容2图片"))
        self.cl2.setText(_translate("Form", "内容2图片预览："))
        self.label_15.setText(_translate("Form", "内容3："))
        self.cb3.setText(_translate("Form", "添加内容3图片"))
        self.cl3.setText(_translate("Form", "内容2图片预览："))
        self.subbt.setText(_translate("Form", "确定提交"))


