# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'news.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(863, 554)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prevButton = QtWidgets.QPushButton(Form)
        self.prevButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_3.addWidget(self.prevButton)
        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_3.addWidget(self.nextButton)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.switchPageLineEdit = QtWidgets.QLineEdit(Form)
        self.switchPageLineEdit.setMaximumSize(QtCore.QSize(20, 16777215))
        self.switchPageLineEdit.setObjectName("switchPageLineEdit")
        self.horizontalLayout_3.addWidget(self.switchPageLineEdit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.switchPageButton = QtWidgets.QPushButton(Form)
        self.switchPageButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.switchPageButton.setObjectName("switchPageButton")
        self.horizontalLayout_3.addWidget(self.switchPageButton)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("color: rgb(255, 85, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.addnew = QtWidgets.QPushButton(Form)
        self.addnew.setObjectName("addnew")
        self.horizontalLayout_3.addWidget(self.addnew)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setStyleSheet("background-color: rgba(255, 255, 127, 200);")
        self.tableView.setAutoScroll(False)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setHighlightSections(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(True)
        self.tableView.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.totalPageLabel = QtWidgets.QLabel(Form)
        self.totalPageLabel.setStyleSheet("color: rgb(255, 255, 0);")
        self.totalPageLabel.setObjectName("totalPageLabel")
        self.horizontalLayout.addWidget(self.totalPageLabel)
        self.currentPageLabel = QtWidgets.QLabel(Form)
        self.currentPageLabel.setStyleSheet("color: rgb(255, 255, 0);")
        self.currentPageLabel.setObjectName("currentPageLabel")
        self.horizontalLayout.addWidget(self.currentPageLabel)
        self.totalRecordLabel = QtWidgets.QLabel(Form)
        self.totalRecordLabel.setStyleSheet("color: rgb(255, 255, 0);")
        self.totalRecordLabel.setObjectName("totalRecordLabel")
        self.horizontalLayout.addWidget(self.totalRecordLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "新闻列表"))
        self.prevButton.setText(_translate("Form", "上一页"))
        self.nextButton.setText(_translate("Form", "下一页"))
        self.label_2.setText(_translate("Form", "转到第"))
        self.label_3.setText(_translate("Form", "页"))
        self.switchPageButton.setText(_translate("Form", "GO"))
        self.label.setText(_translate("Form", "双击编辑新闻，右键删除新闻"))
        self.addnew.setText(_translate("Form", "添加新闻"))
        self.totalPageLabel.setText(_translate("Form", "TextLabel"))
        self.currentPageLabel.setText(_translate("Form", "TextLabel"))
        self.totalRecordLabel.setText(_translate("Form", "TextLabel"))


